[package]
name = "syntesuite"
version = "0.7.0"
edition = "2021"
authors = ["Franklin Delehelle <delehelle@ens.fr>"]
license = "CECILL-C"
description = "TODO"
homepage = "https://github.com/delehef/syntesuite"
repository = "https://github.com/delehef/syntesuite"
readme = "CHANGELOG.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
colored = "3"
derive_more = { version = "2.1.1", features = ["from", "into", "deref", "debug", "display", "try_from"] }
flate2 = "1"
log = "0.4"
regex-lite = "0.1"
rusqlite = "0.40"
thiserror = "2"

[package.metadata.release]
tag-prefix = ""
publish = false
pre-release-hook = ["git-cliff", "-o", "CHANGELOG.md", "--tag", "{{version}}"]
allow-branch = ["master"]
